[tool.black]
line-length = 88
# target-version optionally controls black's formatting targets - leave default auto-detection

[tool.isort]
# Make isort compatible with black output formatting
profile = "black"
line_length = 88
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true

[tool.flake8]
max-line-length = 80
# Recommended to avoid conflicts with black (E203 and W503)
extend-ignore = ["E203", "W503"]
exclude = ["venv", ".venv"]
