[tool.black]
line-length = 80
# target-version optionally controls black's formatting targets - leave default auto-detection

[tool.isort]
# Make isort compatible with black output formatting
profile = "black"
line_length = 80
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
