---
apiVersion: v2
name: kimberly-api
description: Helm chart for Kimberly API service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kimberly
  - api
  - rest
maintainers:
  - name: Kimberly Team
home: https://github.com/cmh-demos/kimberly
